apiVersion: v1
kind: Pod
metadata:
  name: cm-sec-pod3
  namespace: {{.Values.namespace}}
  labels:
    app: cm-sec-pod3
spec:
  containers:
  - image: ubuntu
    envFrom:
      - configMapRef:
          name: cm-sec-cm
      - secretRef:
          name: cm-sec-sec
    volumeMounts:
    - name: config
      mountPath: /config
      readOnly: true
    - name: secret
      mountPath: /secret
      readOnly: true

    command:
      - "sleep"
      - "3600"
    resources:
      requests:
        cpu: "50m"
        memory: "100Mi"
      limits:
        cpu: "50m"
        memory: "100Mi"
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
  volumes: 
    - name: config
      configMap:
        # Provide the name of the ConfigMap you want to mount.
        name: cm-sec-cm
    - name: secret
      secret:
        # Provide the name of the ConfigMap you want to mount.
        secretName: cm-sec-sec
        # default setting; "cm-sec-sec" must exist
        optional: false  