apiVersion: v1
kind: Pod
metadata:
  name: {{.Values.pod1.name}}
  namespace: {{.Values.namespace}}
  labels:
    app: cm-sec-pod
spec:
  containers:
  - image: ubuntu
    env:
      - name: PLAYER_INITIAL_LIVES
        valueFrom:
          configMapKeyRef:
            name : cm-sec-cm
            key: player_initial_lives
      - name: UI_PROPERTIES_FILE_NAME
        valueFrom:
          configMapKeyRef:
            name : cm-sec-cm
            key: ui_properties_file_name
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name : cm-sec-sec
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name : cm-sec-sec
            key: password
      
    command:
      - "sleep"
      - "3600"
    resources:
      requests:
        cpu: {{.Values.pod1.resources.requests.cpu}}
        memory: {{.Values.pod1.resources.requests.memory}}
      limits:
        cpu: {{.Values.pod1.resources.limits.cpu}}
        memory: {{.Values.pod1.resources.limits.memory}}
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always