apiVersion: v1
kind: Pod
metadata:
  name: cm-sec-pod2
  namespace: {{.Values.namespace}}
  labels:
    app: cm-sec-pod2
spec:
  containers:
  - image: ubuntu
    env:
      - name: PLAYER_INITIAL_LIVES
        valueFrom:
          configMapKeyRef:
            name : cm-sec-cm
            key: player_initial_lives
      - name: UI_PROPERTIES_FILE_NAME
        valueFrom:
          configMapKeyRef:
            name : cm-sec-cm
            key: ui_properties_file_name
    volumeMounts:
    - name: config
      mountPath: /config
      readOnly: true
    - name: secret
      mountPath: /secret
      readOnly: true

    command:
      - "sleep"
      - "3600"
    resources:
      requests:
        cpu: "50m"
        memory: "100Mi"
      limits:
        cpu: "50m"
        memory: "100Mi"
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
  volumes: 
    - name: config
      configMap:
        # Provide the name of the ConfigMap you want to mount.
        name: cm-sec-cm
        # An array of keys from the ConfigMap to create as files
        items:
        - key: "game.properties"
          path: "game.properties"
        - key: "user-interface.properties"
          path: "user-interface.properties"
    - name: secret
      secret:
        # Provide the name of the ConfigMap you want to mount.
        secretName: cm-sec-sec
        optional: true
